// src/data.js
const cats = [
  {
    id: 1,
    image: "/images/cats/misty.webp",
    name: "Misty",
    description: "Sweet and gentle cat who loves sunny naps and gentle cuddles",
    sex: "Female",
    age: "2 years",
    breed: "Domestic shorthair",
    castration: true,
    adopted: false,
  },
  {
    id: 2,
    image: "/images/cats/oliver.webp",
    name: "Oliver",
    description: "Playful explorer who enjoys chasing toys and climbing high places.",
    sex: "Male",
    age: "1 year",
    breed: "Tabby mix",
    castration: false,
    adopted: false,
  },
  {
    id: 3,
    image: "/images/cats/luna.webp",
    name: "Luna",
    description: "Shy at first but turns into a loving lap cat once she trusts you.",
    sex: "Female",
    age: "3 years",
    breed: "Tuxedo cat",
    castration: true,
    adopted: true,
  },
  {
    id: 4,
    image: "/images/cats/biscuit.webp",
    name: "Biscuit",
    description: "Loves chasing toys and climbing cat trees.",
    sex: "Male",
    age: "2 years",
    breed: "Domestic shorthair",
    castration: true,
    adopted: false,
  },
  {
    id: 5,
    image: "/images/cats/daisy.webp",
    name: "Daisy",
    description: "Loves chin scratches and curling up in warm, cozy spots.",
    sex: "Female",
    age: "10 months",
    breed: "Calico cat",
    castration: true,
    adopted: false,
  },
  {
    id: 6,
    image: "/images/cats/milo.webp",
    name: "Milo",
    description: "Energetic and loves to explore every corner of the house.",
    sex: "Male",
    age: "1 year",
    breed: "Domestic shorthair",
    castration: false,
    adopted: false,
  },
  {
    id: 7,
    image: "/images/cats/bella.webp",
    name: "Bella",
    description: "Kind-hearted and gentle, great with children and other pets.",
    sex: "Female",
    age: "2 years",
    breed: "Mixed breed",
    castration: true,
    adopted: true,
  },
  {
    id: 8,
    image: "/images/cats/muffin.webp",
    name: "Muffin",
    description: "Social cuddle bug who would love a home with another pet.",
    sex: "Male",
    age: "3 months",
    breed: "Tabby",
    castration: true,
    adopted: false,
  },
  {
    id: 9,
    image: "/images/cats/snowball.webp",
    name: "Snowball",
    description: "Quiet and calm, loves to sit by the window and watch the world.",
    sex: "Male",
    age: "6 years",
    breed: "Domestic longhair",
    castration: true,
    adopted: false,
  },
  {
    id: 10,
    image: "/images/cats/max.webp",
    name: "Max",
    description: "Curious black cat who loves chasing toys and curling up in your lap.",
    sex: "Male",
    age: "2 years",
    breed: "Black cat",
    castration: false,
    adopted: false,
  },
  {
    id: 11,
    image: "/images/cats/nela.webp",
    name: "Nela",
    description: "Affectionate and sweet, always ready for playtime or a nap.",
    sex: "Female",
    age: "11 months",
    breed: "Domestic Shorthair",
    castration: true,
    adopted: false,
  },
  {
    id: 12,
    image: "/images/cats/pumpkin.webp",
    name: "Pumpkin",
    description: "Curious food lover who enjoys belly rubs and chasing his tail.",
    sex: "Male",
    age: "7 Months",
    breed: "Orange",
    castration: true,
    adopted: true,
  },
];

export default cats;
